### ISSUE TITLE
Users Entity 생성

### ISSUE THREAD

**Issue by nswon** [Mojaty/Mojaty_Backend#2]
Users Entity를 생성합니다.
 필드에는 이메일, 비밀번호, 권한, 직업이 있습니다. 직업은 학생과 개발자로 나누었습니다. 기능이 점점 더 추가됨에 따라서 직업도 추가해야 합니다. 
메서드인 addUserAuthority와 encodedPassword는 회원가입할 때 사용됩니다. 각각의 기능은 다음과 같습니다. 

> addUserAuthority -> USER권한을 부여
> encodedPassword -> 비밀번호 암호화

암호화 메서드에 쓰인 PasswordEncoder는 나중에 빈으로 등록해야 합니다.

**Comment by wonyongChoi05** [comment]
SecurityConfig 클래스에 빈으로 등록되어 있습니다.
